SistemaWebVuelos/Models/Vuelo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SistemaWebVuelos.Models
{
    public class Vuelo
    {
        [Key]
        public int Id { get; set; }

        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Fecha { get; set; }

        [Required]
        [MaxLength(50)]
        public string Destino { get; set; }

        [Required]
        [MaxLength(50)]
        public string Origen { get; set; }

        [Range(100, 1000)]
        public int Matricula { get; set; }
    }
}

SistemaWebVuelos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaWebVuelos.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Fecha = DateTime.Now.ToString();
            return View();
        }
    }
}

SistemaWebVuelos/Controllers/VueloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaWebVuelos.Data;
using SistemaWebVuelos.Filters;
using SistemaWebVuelos.Models;
using SistemaWebVuelos.Repository;

namespace SistemaWebVuelos.Controllers
{
    [MyFilterAction]
    public class VueloController : Controller
    {
        private DbVueloContext context = new DbVueloContext();

        // GET: Vuelo
        public ActionResult Index()
        {
            return View("Index", AdmVuelo.Listar());
        }

        [HttpGet] 
        public ActionResult Create()
        {
            Vuelo vuelo = new Vuelo();
            return View("Create", vuelo);
        }

        [HttpPost]
        public ActionResult Create(Vuelo vuelo)
        {
            if (ModelState.IsValid)
            {
                int filasAfectadas = AdmVuelo.Insertar(vuelo);
                if (filasAfectadas > 0)
                {
                    return View("Index", AdmVuelo.Listar());
                }
            }

            return View("Create", vuelo);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Vuelo vuelo = AdmVuelo.Buscar(id);

            if (vuelo != null)
            {
                return View("Edit", vuelo);
            }
            else
                return HttpNotFound();

        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed(Vuelo vuelo)
        {
            if (ModelState.IsValid)
            {
                AdmVuelo.Editar(vuelo);
                return RedirectToAction("Index");
            }

            return View("Edit", vuelo);
        }

        public ActionResult Detail(int id)
        {
            Vuelo vuelo = AdmVuelo.Buscar(id);

            if (vuelo != null)
            {
                return View("Detail", vuelo);
            }
            else
                return HttpNotFound();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Vuelo vuelo = AdmVuelo.Buscar(id);

            if (vuelo != null)
            { 
                return View("Delete", vuelo);
            }
            else
                return HttpNotFound();
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Vuelo vuelo = AdmVuelo.Buscar(id);

            AdmVuelo.Eliminar(vuelo);
            return RedirectToAction("Index");
        }

        public ActionResult BuscarPorDestino(string destino)
        {
            if (destino != null)
            {
                var vuelos = (from v in context.Vuelos
                              where v.Destino == destino
                              select v).ToList();

                return View("Index", vuelos);
            }
            else
                return RedirectToAction("Index");
        }
    }
}

SistemaWebVuelos/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <h3>@ViewBag.Fecha</h3>
    <h1>Bienvenido al sitio web!</h1>
    @Html.ActionLink("Ir a vuelos", "Index", "Vuelo")

</body>
</html>

SistemaWebVuelos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body>

    <div class="header">
        <h1>Sistema VUELOS</h1>
    </div>


    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Vuelos</a></li>
        </ul>
    </nav>
    
    <div class="main">
        <div class="opcional">
            <p>Zona editable opcional</p>
        </div>

        <div class="editable">
            @RenderBody()
        </div>
    </div>


    <footer>
        <p><i>Info@vuelo.com</i></p>
    </footer>

</body>
</html>

SistemaWebVuelos/Views/Vuelo/BuscarPorDestino.cshtml
@model IEnumerable<SistemaWebVuelos.Models.Vuelo>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BuscarPorDestino</title>
</head>
<body>
    <p class="btn">@Html.ActionLink("Nuevo", "Create", "Vuelo")</p>
    <table>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Fecha) </th>
            <th>@Html.DisplayNameFor(model => model.Destino)</th>
            <th>@Html.DisplayNameFor(model => model.Origen)</th>
            <th>@Html.DisplayNameFor(model => model.Matricula)</th>
            <th>Detalle</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Fecha) </td>
                <td>@Html.DisplayFor(modelItem => item.Destino)</td>
                <td>@Html.DisplayFor(modelItem => item.Origen)</td>
                <td>@Html.DisplayFor(modelItem => item.Matricula)</td>
                <td>
                    @Html.ActionLink("Detalle", "Detail", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</body>
</html>

SistemaWebVuelos/Views/Vuelo/Create.cshtml
@model SistemaWebVuelos.Models.Vuelo
    
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "Vuelo", FormMethod.Post))
    {
        <div>
            @Html.LabelFor(model => model.Id)
            @Html.EditorFor(model => model.Id)
            @Html.ValidationMessageFor(model => model.Id)
        </div>
        <div>
            @Html.LabelFor(model => model.Fecha)
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>
        <div>
            @Html.LabelFor(model => model.Destino)
            @Html.EditorFor(model => model.Destino)
            @Html.ValidationMessageFor(model => model.Destino)
        </div>
        <div>
            @Html.LabelFor(model => model.Origen)
            @Html.EditorFor(model => model.Origen)
            @Html.ValidationMessageFor(model => model.Origen)
        </div>
        <div>
            @Html.LabelFor(model => model.Matricula)
            @Html.EditorFor(model => model.Matricula)
            @Html.ValidationMessageFor(model => model.Matricula)
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
        @Html.ActionLink("Volver al index", "Index", "Vuelo")
    }


</body>
</html>

SistemaWebVuelos/Views/Vuelo/Delete.cshtml
@model SistemaWebVuelos.Models.Vuelo

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h2>¿Desea eliminar?</h2>
    @using (Html.BeginForm("Delete", "Vuelo", FormMethod.Post))
    {
        <fieldset>
            <legend>Detalle del vuelo</legend>
            <div>
                @Html.DisplayNameFor(model => model.Id)
            </div>
            <div>
                @Html.DisplayFor(model => model.Id)
            </div>

            <div>
                @Html.DisplayFor(model => model.Fecha)
            </div>
            <div>
                @Html.DisplayFor(model => model.Fecha)
            </div>

            <div>
                @Html.DisplayNameFor(model => model.Destino)
            </div>
            <div>
                @Html.DisplayFor(model => model.Destino)
            </div>

            <div>
                @Html.DisplayFor(model => model.Origen)
            </div>
            <div>
                @Html.DisplayFor(model => model.Origen)
            </div>

            <div>
                @Html.DisplayFor(model => model.Matricula)
            </div>
            <div>
                @Html.DisplayFor(model => model.Matricula)
            </div>
        </fieldset>

        <p>
            <input type="submit" value="SI" />
        </p>

        <p>
            @Html.ActionLink("Volver al index", "Index", "Vuelo")
        </p>
    }
</body>
</html>

SistemaWebVuelos/Views/Vuelo/Detail.cshtml
@model SistemaWebVuelos.Models.Vuelo

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detail</title>
</head>
<body>
    <fieldset>
        <legend>Detalle del vuelo</legend>

        <div>
            @Html.DisplayNameFor(model => model.Id)
        </div>
        <div> 
            @Html.DisplayFor(model => model.Id)
        </div>


        <div>
            @Html.DisplayNameFor(model => model.Fecha)
        </div>
        <div>
            @Html.DisplayFor(model => model.Fecha)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Destino)
        </div>
        <div>
            @Html.DisplayFor(model => model.Destino)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Origen)
        </div>
        <div>
            @Html.DisplayFor(model => model.Origen)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Matricula)
        </div>
        <div>
            @Html.DisplayFor(model => model.Matricula)
        </div>
    </fieldset>

    <p>
        @Html.ActionLink("Volver al index", "Index", "Vuelo")
    </p>
</body>
</html>

SistemaWebVuelos/Views/Vuelo/Edit.cshtml
@model SistemaWebVuelos.Models.Vuelo

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm("Edit", "Vuelo", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Id)
        <div>
            @Html.LabelFor(model => model.Fecha)
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>
        <div>
            @Html.LabelFor(model => model.Destino)
            @Html.EditorFor(model => model.Destino)
            @Html.ValidationMessageFor(model => model.Destino)
        </div>
        <div>
            @Html.LabelFor(model => model.Origen)
            @Html.EditorFor(model => model.Origen)
            @Html.ValidationMessageFor(model => model.Origen)
        </div>
        <div>
            @Html.LabelFor(model => model.Matricula)
            @Html.EditorFor(model => model.Matricula)
            @Html.ValidationMessageFor(model => model.Matricula)
        </div>
        <p>
            <input type="submit" value="Guardar" />
        </p>
        @Html.ActionLink("Volver al index", "Index", "Vuelo")
    }


</body>
</html>

SistemaWebVuelos/Views/Vuelo/Index.cshtml
@model IEnumerable<SistemaWebVuelos.Models.Vuelo>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p class="btn">@Html.ActionLink("Nuevo", "Create", "Vuelo")</p>
    <table>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Fecha) </th>
            <th>@Html.DisplayNameFor(model => model.Destino)</th>
            <th>@Html.DisplayNameFor(model => model.Origen)</th>
            <th>@Html.DisplayNameFor(model => model.Matricula)</th>
            <th>Detalle</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Fecha) </td>
                <td>@Html.DisplayFor(modelItem => item.Destino)</td>
                <td>@Html.DisplayFor(modelItem => item.Origen)</td>
                <td>@Html.DisplayFor(modelItem => item.Matricula)</td>
                <td>
                    @Html.ActionLink("Detalle", "Detail", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</body>
</html>